apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-secrets
    namespace: homepage
spec:
    secretTemplates:
        - name: homepage-secrets
          stringData:
            BAZARR_API_KEY: ENC[AES256_GCM,data:I6pm5er6rh9EyUv1gUMr4Xx5KWq6hspFBP11UtjHwLk=,iv:WrkmDE8q7g0cKuX1L0f+fDmB/egGZ1Ow+MWzbJ/9Q4Y=,tag:3qrdJcMaNigpMkxKPCIWEQ==,type:str]
            SONARR_API_KEY: ENC[AES256_GCM,data:zzFB/hRxXCfYd7Eg2xri5BlKrNkLOP/gFM2sfEx3y8A=,iv:TxbzPupjzMo8ZrJq+hNCfV/rNbWFkxNSGPOZY8ZQOF4=,tag:J1ZwBjwtqlYqAlCSVjHJFQ==,type:str]
            RADARR_API_KEY: ENC[AES256_GCM,data:iJjlp6YTG+1qIFD/hCo5IPidmQRnJwUzcSrUcWfcbHc=,iv:82BpzPqQF8QKozTyfOt1qFFknDO7Qcr57EqcYST6Jxw=,tag:0nqVou69penuJwQwWFBpaw==,type:str]
            PROWLARR_API_KEY: ENC[AES256_GCM,data:1FOqKACHSXOdWWUdG66tUg/jNk7BSWZqp9uMcXAs3b0=,iv:qdr4Csyn3rTXERlCydqGgtn0rmXi7jWephUs+F1r9x0=,tag:15tUHqUByTRmDwGOKx9A7Q==,type:str]
            JELLYSEER_API_KEY: ENC[AES256_GCM,data:i99pLJEhbLlmqpBIlUkUnwggfKj3mrgdy4BeWb/YbFOytOrZM+EkikgyI7nVfmV3J5OY2fMk2qoWLQcOiCciR+qAbz4=,iv:sGcX6Mycl0TWSdviF42y7kOU4egw5+sL+qRMZnW2MkE=,tag:bm6Tahb1IkPWNb6RTg+7RQ==,type:str]
            JELLYFIN_API_KEY: ENC[AES256_GCM,data:4PG6HxSHUw65vFeB79VlVd1vrcLUBUDea8c1RzcA0vI=,iv:rwhOq1HfXg/UzMYUZ6a7dZuFw0FoG6Nk5MsAPVr/wu8=,tag:deYH/KNmCskW+/o8Uc2Uww==,type:str]
            ROMM_PASSWORD: ENC[AES256_GCM,data:2mWU9yHFowU/eHx6vw==,iv:bTqyrWjTsgml5b9+1wb1hJ2XlxK16Mv3rdSU1cLGc14=,tag:z9GFuGz6TIUUcEKFdok6vA==,type:str]
            QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:9Aesalkw,iv:2n7FVY9kToDPh+gM3oKg6QPjnTKipQ0cpkUaRY5HyO0=,tag:ZSDjWTpT7nNhXxfbWuqh4Q==,type:str]
            CLOUDFLARE_TUNNEL_KEY: ENC[AES256_GCM,data:ilbADsG4QqKrPOf2rZW32r8aXEhLxeZVp6cor1V+GYwc1/tkYegXcA==,iv:QSFwMBBqM/3pGlSUfo4mcqJdeWuxKZXBMjGKQieuDLg=,tag:MVXvjVViveDfY8+Y2AFmhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUlJiQzJhZGdZRExJOUFL
            MmZVaDV0T0JrWlZNK0FiZi9Yb29uTkx4ZlZJCmtqTlVteGJOWXF0dmduRk5uLzcw
            amlJM3A2RUVkek50ZmFOQnVnVW9wN0EKLS0tIHNrUE5ONWEyaEZIUzl3dEFuTzVy
            MDU4UlBPeDMwZFhTWjZqbkEybEpwTUUKt2LsMjo37UOwA+Rrb07yzevRRTqg8KQs
            nXm+ZSIHWCaRUugKPsRXwcjGJ/Bp8h2K6vHIfpzbNYCSzWBPJXZKzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h4azg8f0prh7rezk5s7zj7glg2w2y64ze6gfrzrq8mrcxz8sjqus2ycwcn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T22:19:40Z"
    mac: ENC[AES256_GCM,data:k37zYUPlOVetbVDXf50VIVmt3eaCgeCASEgl7E41MlhrT0uFCJRE2zAz60xjl0lWZE56krej3F+i+qsdsA1cpsmPB3hpE0LPUAA7Fkinr3CC5jfKB2qT46R3ml3uigf/IdvtxXFV0CzUEZhRm6Q80ykmkb8vQbZ62/QcZaAnhlI=,iv:FB4Gcj1E0/Z0gqTBcTJNVzLU7lhKcyPTtcWKRohLFmk=,tag:oTWsH7faiMAcv3MjhYZrQg==,type:str]
    version: 3.13.3
