{{- if .Values.longhorn.enabled }}
{{- range $keyId, $value := .Values.longhorn.persistentVolumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $keyId }}-pvc
  labels:
    app.kubernetes.io/managed-by: media-storage
spec:
  accessModes:
    - {{ $value.accessModes | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ $value.storageSize }}
  storageClassName: {{ $value.storageClassName | default $.Values.longhorn.storageClassName | default "longhorn-ssd" }}
{{- end }}
{{- end }}
