kumaUrl: "http://uptime.uptime.svc.cluster.local:80"

resyncInterval: "300"
logLevel: "INFO"

credentials:
  existingSecret: "uptime-kuma-reconciler-creds"
  username: ""
  password: ""

image:
  repository: python
  tag: "3.11-slim"
  pullPolicy: IfNotPresent
  useCustomImage: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

staticMonitors:
  enabled: true
  monitors:
    - name: egbp (Pi)
      type: ping
      hostname: 10.0.0.29
      group: Infrastructure
      interval: 60
    - name: egbp-nuc
      type: ping
      hostname: 10.0.0.23
      group: Infrastructure
      interval: 60
