apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-bot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # after temporal (wave 0)
spec:
  project: default
  source:
    repoURL: git@github.com:Kakuhiry/homelab-charts.git
    targetRevision: HEAD
    path: discord-bot
  destination:
    server: https://kubernetes.default.svc
    namespace: filestash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
