apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/egarcia-br/homelab-charts.git
    targetRevision: HEAD
    path: media-storage
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
