apiVersion: v1
kind: Service
metadata:
  name: {{ include "aria2.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aria2.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "aria2.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
