apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: torklink-ws
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: torklink
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host("torlink.gbklabs.com")
      middlewares:
        - name: torklink-ws
      services:
        - name: torklink
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host("torklink-files.gbklabs.com")
      services:
        - name: filebrowser
          port: 80
