apiVersion: v1
kind: Service
metadata:
  name: torklink
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: torklink
  ports:
    - port: 80
      targetPort: 7681
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: filebrowser
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
