{{- range .Values.recurringJobs }}
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: {{ .name }}
  namespace: longhorn
spec:
  name: {{ .name }}
  cron: {{ .cron | quote }}
  task: {{ .task }}
  groups: [{{ .group }}]
  retain: {{ .retain }}
  concurrency: {{ .concurrency }}
  labels: {}
{{- end }}
