apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-credentials
    namespace: monitoring
spec:
    secretTemplates:
        - name: grafana-credentials
          stringData:
            admin-user: ENC[AES256_GCM,data:EtxCjOY=,iv:vGladAFplqQH0CxAhMJMzFmK9Mcim61wA5xNPRAwkeg=,tag:s97aEv3beqUBUVrLns54iw==,type:str]
            admin-password: ENC[AES256_GCM,data:SRTf6PC3TgCmsKw=,iv:EpSyykekPXjLC7b7btsBKlHf+/1mgQaazWvj1vADLY0=,tag:x/jo8hj3k8q7xtmXoF8tiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bGw5c3hHNkxMeXcvSFgy
            Z1JnVXZYY1NqS2dEWVptQ2pIeWw3bU41OWowCm13QkpRelRLU21LaUZaSjlVeEMy
            bU5mQ0tMdGJoY3BSajdpMGtXeVdTZUEKLS0tIG56YTFRa3VucyszUFZsUUU3ajZP
            eG5JWW1lWkttYkQxckd6UHRjYmVRZlkKG++3YKQgZxx0m1NcSxH16tP9uKCX4J1a
            sTq4ubz2k7Ph8AGFRrh7krdB0QCXpZPaIYjxODIjD3JvodYc9CcYKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h4azg8f0prh7rezk5s7zj7glg2w2y64ze6gfrzrq8mrcxz8sjqus2ycwcn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T22:54:58Z"
    mac: ENC[AES256_GCM,data:0/1l6ysO3YmLB/pRx1RDmLacQpvjkTELDPy3QmK7AKOstRc+xkzaByfOg+18yUtdvMAJwRSAK47C70glKmPUR+iBmeProyax4LQsdi8JpPEZ8S5ybnB+uNlXqa8huHdr+HmhksazxEeGG45WkH3rtuLGAxjIIUrs5TLCNZh2ngc=,iv:Dacnc2Z+R1fQlDg98OMAuxl+/t3Pu3WVIfEfogNrMWo=,tag:bRsmm5ED5kA8a4aDXZGlJg==,type:str]
    version: 3.13.3
