apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host("grafana.gbklabs.com")
      services:
        - name: grafana
          port: 80
  tls:
    secretName: wildcard-secret
