apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: romm-secret
    namespace: romm
spec:
    secretTemplates:
        - name: romm-secret
          stringData:
            DB_PASSWD: ENC[AES256_GCM,data:kcH8C4wdHjc=,iv:46j8INf6p7fus2GBHCp8HRmJdZXWuXMsvdez1U8HIHE=,tag:QnSNJi/OleEXYtYd/Ay3bw==,type:str]
            DB_USER: ENC[AES256_GCM,data:O79wzRq3L5g=,iv:7Va2sSiBqf+GNjgL8ao60YvNZUoM8eI9j0yxyhbrjig=,tag:GerFu4GgPYd+MIP/HVQU5w==,type:str]
            IGDB_CLIENT_ID: ""
            IGDB_CLIENT_SECRET: ""
            MARIADB_PASSWORD: ENC[AES256_GCM,data:qfZiKXTcaNg=,iv:PuwjWCi9HO//YX0erfRr6KWrcGfo3bf+NoeQNIseW3I=,tag:UlTA1EnQQJZu/0h5FgkhVA==,type:str]
            MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:lFdr+gct4Zo=,iv:GKFBT6rLV2wwSP2A17azJdN0NDfbKcKoJB5ipRPf3Yo=,tag:X/TlTOIvBpcoCBDBaQNyag==,type:str]
            MARIADB_USER: ENC[AES256_GCM,data:JX8MCXWjAcM=,iv:2PnGTxkPj12YLTzZZ38UQDgVLbCS3gtsxzewU0GV0DQ=,tag:sN1Qdl2FIwA0R7ZuFCTxZA==,type:str]
            ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:EOIopwS0GJo=,iv:Yl1K3p+BJod/8irhxp6vCea/Xy8btXoYX61rTm493SE=,tag:TAHrZz/H3sj6QnF0YJGlMg==,type:str]
            STEAMGRIDDB_API_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc3NWYWlLWDZ6TDhJUEVL
            UzJoOWxZU2pxYXVURWtwTjlVMUp2WVR1akM0CndkdlhIMUwreU1SbFE5TXRObnda
            Zjlvemp6SGRMZGp5aWhFeEdnR3hlTHcKLS0tIHZSYlRjeHpqR1pvbXdCbGRUekhI
            aUZTRlgxS3I3RmozdTlscmF5THhLZXMKV37a2X8BaNiyS7r9HJQYm8724L2XxCOh
            Of0W+/xSlI2Xl6PvEU6TLQN43FLC7S0ORYHCY0VuvRpGiyQQ2mEklg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h4azg8f0prh7rezk5s7zj7glg2w2y64ze6gfrzrq8mrcxz8sjqus2ycwcn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T23:20:59Z"
    mac: ENC[AES256_GCM,data:/135ihfnDxXykiWyv52QfoQBwfHZ+YIgpKH1TGUUbCVWdvS5Pp/+y6bpnkQUZEvzugnMTuzIRBwdyWANojfCU1Lf6QW5WBtYPVDo1qsZUubfUPLPBYAKr/ZfaK21J94HCAVbmYrJ6zClDsOpIUMbTta19ybDwNbQAF6hCNTNXck=,iv:85CcdlZaTNXWYXPm06EjC+rb5PEJ5Sp+75Ix20+B2lk=,tag:LeEAqJD9bMXG5t6+KZnOnw==,type:str]
    version: 3.13.3
