apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: romm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:Kakuhiry/homelab-charts.git
    targetRevision: HEAD
    path: romm
  destination:
    server: https://kubernetes.default.svc
    namespace: romm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
