apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-secret
    namespace: torklink
spec:
    secretTemplates:
        - name: immich-secret
          stringData:
            DB_USERNAME: ENC[AES256_GCM,data:PrRNftPa,iv:xN7XaPFzHH0UcGHadoo+bdAEkqHmfT8iWfM3Wj+m1bA=,tag:RemukM2g4+Oz82crDEBtgg==,type:str]
            DB_PASSWORD: ENC[AES256_GCM,data:RQvg8zdBM2PnmlhLW36WBm2f0BLOHGrr68fB3XZA4ePPzmEuxJ+7TOGAUv37syrV,iv:U+SjsclSrKbDYNLBjrLaipq1zFyiIziW1g3521m0Mq4=,tag:aoKZm5KrvY/uYYxaRGzxGg==,type:str]
            DB_DATABASE_NAME: ENC[AES256_GCM,data:McMNWpMk,iv:e6qlL1Re4EN0GIqfp2ml0hMrozrWTPdZ5EZEs7ZbRW0=,tag:dnlSE8qnz7Ue1B9cSc46fA==,type:str]
            POSTGRES_USER: ENC[AES256_GCM,data:fr8tNt4y,iv:x81lN9xh/RaCz/VpuQ1TP4TbaKkfQYUuFI3TQ74KmqU=,tag:wBkh0a8SOsuLOEMWo/LmCA==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:zewdQeytB7m0vNNzvZSW3MWMQ52IXooGjdCXHvyG5AF+jdoJImNQi6BEQOMUmuIY,iv:0QpTS1fTwGHmIoOwYRQckwhx3weGmZ+nEgQVqMxC4ys=,tag:N3wynmlvDuqzuErGhsd1uw==,type:str]
            POSTGRES_DB: ENC[AES256_GCM,data:BsHZIAxb,iv:stzyLJse1qXpiwDYBdhkWHnLTgyNoYnvpJfpA7elVhk=,tag:uOgVx7TJ9Q0lz5ASVSc44Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaUY4U3JaalR5VlFtRzkr
            ZTJKdXU0L2VacXJGaGVCU2RPSDVscytYaWhZCnlvbDdlQ3k0MEhBYW10ZmsvRXFJ
            NSsrcVhvUG1ocUZCWDFOY1FsdTZTZXcKLS0tIGRqeDkrbDg4UTYyQ1hNWjlRYU02
            YWtFd3ErU1dmb2Q1N21oRXNPcUFGTjgKBLomEX9t7Kk8I7uhqVb0/jUqOryoQZuS
            8Zi6ZHnL8eN/bfgRvcBwE5ebB+ZyWcS+hrV2j2G6EEEyRAShWsKQzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h4azg8f0prh7rezk5s7zj7glg2w2y64ze6gfrzrq8mrcxz8sjqus2ycwcn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T20:11:58Z"
    mac: ENC[AES256_GCM,data:ae/ZcwtQaSuP5KPtovE8ux3EWJlxahdOUmJV0cmU0EZAvTuKZKdqMKkNWjx74mHQEB0WaiEUIRPpFpxW2bNiIR83bMk9W9Bn2uLLuhsqyqFPVegJlBZOkAwXJjlWptZ218L3cp8jRIl83fLASxadeNkUi7IleH4wiR3eeA2USxc=,iv:j9fC3YPJk5UZJKsTjZaShTqBSqmg5sBbTo27hsAV3YE=,tag:n31yUuzE/8q0hvmNLw0IGg==,type:str]
    version: 3.13.3
