apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host("{{ .Values.ingress.host }}")
      services:
        - name: immich-server
          port: 80
