{{- if .Values.postgres.sealedSecrets.enabled}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.postgres.sealedSecrets.name }}
  namespace: immich
spec:
  encryptedData:
    {{- range $keyId, $key :=.Values.postgres.sealedSecrets.secret}}
    {{$keyId}}: {{ $key | quote }}
    {{- end}}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: immich
{{- end}}
