{{- if .Values.sealedSecrets.enabled}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "common.fullname" . }}-secret
  namespace: immich
spec:
  encryptedData:
    {{- range $keyId, $key :=.Values.sealedSecrets.secret}}
    {{$keyId}}: {{ $key | quote }}
    {{- end}}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: immich-secret
      namespace: immich
{{- end}}
