apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rdicidr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:Kakuhiry/homelab-charts.git
    targetRevision: HEAD
    path: rdicidr
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
