apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: temporal-web
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host({{ .Values.webUI.host | quote }})
      services:
        - name: temporal-web
          port: 80
