apiVersion: v1
kind: Service
metadata:
  name: media-nfs
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: media-nfs
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
      protocol: TCP
