apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: {{ .Release.Namespace }}
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: pihole
spec:
  type: NodePort
  selector:
    app: pihole
  ports:
    - name: admin-tcp
      port: 80
      targetPort: 80
      protocol: TCP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-lb
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  {{- if .Values.dnsLoadBalancerIP }}
  loadBalancerIP: {{ .Values.dnsLoadBalancerIP }}
  {{- end }}
  selector:
    app: pihole
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
