apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr
  namespace: {{ .Release.Namespace }}
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/href: https://bazarr.gbklabs.com
    gethomepage.dev/icon: bazarr.svg
    gethomepage.dev/name: Bazarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host("bazarr.gbklabs.com")
      services:
        - name: bazarr
          port: 80
