apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-credentials
    namespace: monitoring
spec:
    secretTemplates:
        - name: minio-credentials
          stringData:
            rootUser: ENC[AES256_GCM,data:JDhGV4WXdFD0zg==,iv:vu/6GmN0sNeu8n7Z+bhnWj14UdaqD+mv6MW7SF49ohg=,tag:6XqdH0hyUrJiMSVdoHYukw==,type:str]
            rootPassword: ENC[AES256_GCM,data:yw3GwQGwromQUPakYw==,iv:bADYOn8DX4DOjp9gnp+X2W7h3wboanM3QwAmukJVhGE=,tag:X1naLkaD7vEcMNnYkCUcmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z3BiRmxCWndidTEwQmp3
            eE5mdzZNNkx1MExQdDN4QSs2NFRaOEEybXlzClkwNHpITHRTdWllRlpWTC8xUWhU
            Q0RwN0ZmY2Vsc3Z1MnhMaGMwTVdtUDgKLS0tIFpwOVFhTjFKbUZTZVp0Q0d5dFZa
            cUJuTmJlakFMeFNpeGNqOVpPVkg5UGsKKw3dDrDuu8jvdacMcTQH9EWv586jFjp8
            oDu+gjw8gmeDyuSIdUKYLrxopsHrvmeBkONtOEWxVNn2+8pfwyia1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h4azg8f0prh7rezk5s7zj7glg2w2y64ze6gfrzrq8mrcxz8sjqus2ycwcn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T22:55:37Z"
    mac: ENC[AES256_GCM,data:FeyshshJgVCnj6uSAPnwWJN4ElKbwu+5wQ1yOW4ah69cWoCpCnSrUnm1jnn/eOMs9DXIdLcmEyZgHe7TG3Hcnw6A1S6mBsbTeaVtrtTp9LlTU9wYVPObjkFHManilZQ4ZOw4l2gOrNinarLNU69P+vSwStqcPDD/RNacEQQOoaY=,iv:nPGMw5Tffgz6txm5/KjTIJeGDbjOr/IJ72BSi0RD2bk=,tag:AuEaBHE0X0RYU7rDmZihMA==,type:str]
    version: 3.13.3
