apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: operator-oauth
    namespace: tailscale
spec:
    secretTemplates:
        - name: operator-oauth
          stringData:
            client_id: ENC[AES256_GCM,data:LqBLOgq/hVFabzALqNXH2F8=,iv:rPgIla2TU+yNh4oiZTsIuCOoNaHm5lfbX2gpw0pRxn8=,tag:AzTbI2hpFdNin5fuepgUZA==,type:str]
            client_secret: ENC[AES256_GCM,data:jumepTjUDVy/CnJjQUafFCSa3iCVmc5Cgg2ukOY3qMjl2rqhIuZu+VS5/fjw/XUtGW49WK2g/ZISw8DIZKQR,iv:9vNOnmXr6A5PprN8ZMuvYOEUQYPWfQM3hcQGoFq2/qQ=,tag:tEEgiiGKlcq/gINi3V1L/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOGJmR0cydHJYUVlueThv
            VXNDYk41elZRbEFxRFNRYTY2ZVd6SU9WbEFvCjFqc0N4dzh2aGlWWUQ1UUtsQlR2
            T3BjcXpSb1ZHSGY5VEZDODVBNGkvK1kKLS0tIGQvU0lvRDZOeFJDYUE3akF4MERZ
            bzVVSTNDZmYraFI3WHdobkU0TERwQk0Ks0ypJB8/K/prmNbmbQxccbS5PfowgK5w
            eW7RM/FjkV4UQTneN9NFysZGsLkWI3l4wr9n/y9R8o6tRBss4EV9WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h4azg8f0prh7rezk5s7zj7glg2w2y64ze6gfrzrq8mrcxz8sjqus2ycwcn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T23:27:46Z"
    mac: ENC[AES256_GCM,data:o+uIuw8v8Q/02fJUE3Qn2AwhOwjQpg2F4f9uv5JXnW3CU+59MfSg29BggutA5jLuTwNlRaWnaqi8S9C7XV99wi9SABMNZ19EIZAb48yeTCWckQ/PitmmOPnZja5maTqviAJXMryvcAQiAaiVbza+K6arfw4I/Mh26mTiXqxj1zo=,iv:By7rTn3vRyTdZsIeSew64am/CTjHdrvPdVJeAorYIZ0=,tag:l47lt/DckBDC3BNYUbIStw==,type:str]
    version: 3.13.3
