apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    events {}
    http {
        upstream pc {
            server 192.168.1.246:11435;
            server 192.168.1.178:11436;
        }
        server {
            listen 80;

            location / {
                proxy_pass http://pc;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }