service:
  type: NodePort
  port: 80
  targetPort: 8096

image:
  tag: '10.9.4'

serviceAccount:
  create: false

ingress:
  enabled: true

longhorn:
  enabled: true
  persistentVolumes:
    jellyfin-conf:
      storageSize: '108447924224'

nfs:
  enabled: true
  pvs:
    jellyfin-storage:
      storageSize: 1T
      path: /mount
      storageClassName: ""
      accessModes: ReadWriteMany

resources:
  limits:
    cpu: "4"
    memory: "6200Mi"
    gpu.intel.com/i915: 1

nodeSelector: {}

env:
  PUID: "0"
  PGID: "0"

persistence:
  config:
    enabled: true
    isPvc: true
    existingClaim: jellyfin-conf-pvc
  data:
    enabled: true
    isPvc: true
    existingClaim: jellyfin-storage-pvc

#"dst":    ["autogroup:internet:*"],