# Default values for bazar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: lscr.io/linuxserver/bazarr
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  targetPort: 6767
  port: 80

env:
  PUID: "0"
  PGID: "0"
  TZ: "Europe/London"

volumeMounts:
  - name: config
    mountPath: /config
  - name: movies
    mountPath: /movies
  - name: tv
    mountPath: /tv

volumes:
  - name: config
    persistentVolumeClaim:
      claimName: bazarr-config-pvc
  - name: movies
    persistentVolumeClaim:
      claimName: media-movies-pvc
  - name: tv
    persistentVolumeClaim:
      claimName: media-tv-pvc

longhorn:
  enabled: true
  persistentVolumes:
    bazarr-config:
      storageSize: 5Gi
      storageClassName: longhorn-ssd

nfs:
  enabled: false

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: bazarr
  tls:
    - hosts:
       - bazarr

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
